### ISSUE TITLE
Gh pages - [Question]

### ISSUE THREAD

**Issue by dantesolis** [brandon-rhodes/Concentric-CSS#6]
What about creating a simple one page and deploy it to `gh-pages` and using `gulp` for the generated css?

**Comment by brandon-rhodes** [comment]
I have not tried that approach before — what advantages does it offer over the native GitHub README viewer and file viewer?

**Comment by dantesolis** [comment]
@brandon-rhodes  not much really, it will perhaps just "save" the readers 1-2 clicks. But not too much difference and I guess it could also put the info "live".  Hosting in `gh-pages` is free. I could take care of all that if you like and submit a PR.

**Comment by brandon-rhodes** [comment]
Having thought about it a bit, I think I prefer to have users go only one place — the official GitHub code viewer (or the GitHub "raw" source rendering) — to find the text, instead of going one of two places.

But I would be happy to accept a pull request that updates the front-page README so that it has links to both the CSS2 and CSS3 files — do you think that would help users who land on the GitHub page and aren't sure what to do?

**Comment by dantesolis** [comment]
I think that could help, it's already quite clear,  but more information and 1-2 links couldn't hurt. I can take care of that and submit a PR.

**Comment by brandon-rhodes** [comment]
Thank you! :)

**Comment by brandon-rhodes** [comment]
I am going to go ahead and close this, but if you get a pull request put together then I'll see it in my notifications and take a look. Thanks!

**Comment by dantesolis** [comment]
Hey @brandon-rhodes, let me then create something and do a PR in the next couple of days.
