### ISSUE TITLE
src missing

### ISSUE THREAD

**Issue by paleite** [brandon-rhodes/Concentric-CSS#8]
Hey there,

src seems to be missing: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src

Thanks!

**Comment by brandon-rhodes** [comment]
This project only intents to suggest an ordering for the CSS “properties” that might apply to an element. Whereas `src` is a descriptor of a rule, and therefore — I don’t think? — cannot ever appear alongside a property like `margin` or `width`. Since it cannot appear alongside them, I'm not sure it would be meaningful to prescribe an ordering that it should have with respect to them?

But if you do know of examples where `src` appears alongside things like `margin`, provide an example for us to think about!
